// Generated by apps/slide/tools/gen-types.mjs from specs/*.schema.json. Do not edit.
/* eslint-disable */

export interface SlideProject {
  specVersion: "1.0.0";
  id: string;
  title: string;
  description?: string;
  theme?: string;
  aspectRatio?: string;
  status: "initialized" | "outlined" | "drafted" | "visualized" | "exported" | "failed";
  pagesCount?: number;
  export?: {
    pdfPath?: string;
    exportedAt?: string;
    sizeBytes?: number;
  };
  updatedAt: string;
  updatedBy?: "user" | "agent";
}

export interface SlideActivity {
  message: string;
  step: "init" | "outline" | "draft" | "visual" | "export" | "idle";
  currentSlide?: number | null;
  totalSlides?: number | null;
  waitingForUser?: boolean;
  updatedAt: string;
}
