// Generated by apps/slide/tools/gen-types.mjs from specs/*.schema.json. Do not edit.
/* eslint-disable */

export interface SlideProject {
  specVersion: "1.0.0";
  id: string;
  title: string;
  description?: string;
  theme?: string;
  aspectRatio?: string;
  status: "initialized" | "outlined" | "drafted" | "visualized" | "exported" | "failed";
  pagesCount?: number;
  export?: {
    pdfPath?: string;
    exportedAt?: string;
    sizeBytes?: number;
  };
  updatedAt: string;
  updatedBy?: "user" | "agent";
}

export interface SlideActivity {
  message: string;
  step: "init" | "outline" | "draft" | "visual" | "export" | "idle";
  currentSlide?: number | null;
  totalSlides?: number | null;
  waitingForUser?: boolean;
  updatedAt: string;
}

/**
 * output/check.json, written by `pnpm run check`: per-slide render findings and screenshots.
 */
export interface SlideCheck {
  checkedAt: string;
  total: number;
  ok: boolean;
  slides: {
    no: number;
    title?: string;
    /**
     * Line in slides.md where the slide starts
     */
    line?: number;
    /**
     * Screenshot path relative to the project root
     */
    image: string;
    issues: {
      type: "overflow" | "clipped" | "unresolved" | "image" | "canvas" | "compile" | "runtime" | "render";
      message: string;
    }[];
  }[];
  /**
   * Problems not tied to one slide, or that stopped the check
   */
  errors: string[];
}
