// Generated by packages/video-core/tools/gen-types.mjs from specs/*.schema.json. Do not edit; run `pnpm run gen:types`.
/* eslint-disable */

/**
 * 專案層級定義與 scene 播放順序。scene 內容與狀態存於各自的 scene.json（SPEC §4.1）。
 */
export interface VideoProjectJson {
  specVersion: string;
  /**
   * 以 `x-` 開頭的欄位保留給使用者或第三方工具自訂，Agent 必須原樣保留。
   */
  project: {
    id: string;
    name: string;
    /**
     * 影片類型：product = 產品介紹（Skill product-video）；story = 把故事做成 SVG 動畫影片（Skill story-video）。
     */
    kind?: "product" | "story";
    /**
     * 影片的來源資料；至少要有哪些依 project.kind 而定。
     */
    sources: {
      productUrl?: string | null;
      /**
       * 產品網址要登入才看得到。為 true 時，使用者須先以 pnpm run login 在瀏覽器視窗自行登入，capture 才能執行（gate productLogin）。帳密不寫入任何檔案。
       */
      requiresLogin?: boolean;
      /**
       * 產品原始碼位置，唯讀輸入，可在專案外（相對或絕對路徑）。
       */
      sourceCodePath?: string | null;
      description?: string | null;
      /**
       * 故事全文、大綱或點子（kind 為 story 時使用）。整理後的定稿在 brief/story.md。
       */
      story?: string | null;
      /**
       * 風格參考影片（可選，SPEC §6.2 Step 2）。
       */
      referenceVideoUrl?: string | null;
    };
    /**
     * 故事的角色與各自的聲音（kind 為 story 時使用）。script.md 中以【name】開頭的行由該角色說；其餘為旁白，用 project.tts。
     */
    cast?: {
      /**
       * 英文小寫識別碼，也是美術資料夾名稱（@/assets/cast/<id>/）。
       */
      id: string;
      /**
       * script.md 中【】內使用的名字。
       */
      name: string;
      /**
       * 外型與個性，給畫圖與挑聲音參考。
       */
      description?: string;
      /**
       * 省略時沿用 project.tts.provider。
       */
      provider?:
        "edge-tts" | "azure" | "openai" | "elevenlabs" | "piper" | "system" | "manual" | "cosyvoice3" | "cosyvoice";
      /**
       * 省略時沿用 project.tts.voice。
       */
      voice?: string;
      /**
       * 角色部件 SVG 所在資料夾，通常為 @/assets/cast/<id>/。
       */
      art?: string;
    }[];
    targetAudience?: string;
    /**
     * 製作中發現某段太趕時：auto = Agent 可自行在限度內調整 scene 長度並事後回報；ask = 每次先詢問使用者。
     */
    durationAdjust?: "auto" | "ask";
    /**
     * 自訂動畫（Agent 撰寫 visual.motion 動畫模組或繪製新的 SVG 插圖，會耗用較多 token）：allow = 全部放行；deny = 不使用；ask = 分鏡審閱時逐段由使用者決定。
     */
    customMotion?: "allow" | "deny" | "ask";
    /**
     * 影片風格與語氣（例如：專業簡報、活潑社群短片），與使用者確認後填寫。
     */
    style?: string;
    /**
     * BCP 47 語言標籤，例如 zh-TW、en、en-US。
     */
    language: string;
    /**
     * 由 /video-translate 產生時記錄來源專案（SPEC §4.4）。
     */
    translatedFrom?: {
      id: string;
      /**
       * BCP 47 語言標籤，例如 zh-TW、en、en-US。
       */
      language: string;
    };
    /**
     * 寬高須符合 aspectRatio（由 validate.mjs 檢查）。H.264 需偶數寬高。
     */
    format: {
      aspectRatio: "16:9" | "9:16" | "1:1" | "4:5";
      width: number;
      height: number;
      fps: 24 | 25 | 30 | 50 | 60;
      targetDurationSec?: number;
    };
    /**
     * BGM 設定，只在 assemble 階段使用（SPEC §7.5）。
     */
    audio?: {
      /**
       * 相對於專案根目錄；null 或檔案不存在時略過 BGM。
       */
      bgm?: string | null;
      bgmVolume?: number;
      ducking?: boolean;
      /**
       * 生成配樂的樂譜（SPEC §7.5）。`pnpm run music` 依此寫出 assets/music/bgm.wav；要當 BGM 使用，audio.bgm 設為該路徑。
       */
      music?: {
        /**
         * auto：有安裝 FluidSynth 與音色庫就用它（真實樂器取樣），否則用 webaudio（程式合成，免安裝）。
         */
        engine?: "auto" | "fluidsynth" | "webaudio";
        /**
         * 曲風模板，決定配器與鼓、鋼琴、貝斯的型態及旋律節奏：pop 輕快科技、warm 溫馨、fairytale 童話、suspense 懸疑科幻（預設無旋律）、anthem 激勵片尾、lofi 慵懶搖擺。
         */
        style?: "pop" | "warm" | "fairytale" | "suspense" | "anthem" | "lofi";
        bpm: number;
        /**
         * 調性，大調寫音名（C、F#、Bb），小調加 m（Am、C#m）。
         */
        key: string;
        /**
         * 旋律與力度的亂數種子；換一個數字就是另一版。
         */
        seed?: number;
        drums?: boolean;
        /**
         * 覆蓋曲風預設的 General MIDI 音色編號（0–127，只影響 fluidsynth）；null 表示不演奏該聲部。
         */
        instruments?: {
          lead?: number | null;
          keys?: number | null;
          pad?: number | null;
          bass?: number | null;
        };
        /**
         * fluidsynth 各聲部使用的音色庫（~/.aoa/soundfonts/ 內的檔名，由 pnpm run music:setup 安裝）；未指定的聲部用 default，default 未指定時用 GeneralUser-GS.sf2。指定的檔案不存在時改用預設並警告。
         */
        soundfonts?: {
          default?: string;
          lead?: string;
          keys?: string;
          pad?: string;
          bass?: string;
          drums?: string;
        };
        /**
         * 各聲部音量增減（dB，0 為原始平衡）。兩種引擎都適用。
         */
        mix?: {
          lead?: number;
          keys?: number;
          pad?: number;
          bass?: number;
          drums?: number;
        };
        /**
         * 依序演奏的段落。長度用 bars（小節數）或 scenes（對齊這些 scene 在成片中的總長，需已渲染）擇一指定。
         *
         * @minItems 1
         * @maxItems 32
         */
        sections: [
          {
            name?: string;
            bars?: number;
            /**
             * @minItems 1
             */
            scenes?: [string, ...string[]];
            /**
             * 每小節一個和弦，不足時循環。例：C、Am、F#m、Bb、G7、Cmaj7、Dsus4。
             *
             * @minItems 1
             * @maxItems 16
             */
            chords:
              | [string]
              | [string, string]
              | [string, string, string]
              | [string, string, string, string]
              | [string, string, string, string, string]
              | [string, string, string, string, string, string]
              | [string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string, string, string, string, string]
              | [
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string
                ]
              | [
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string
                ]
              | [
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string
                ];
            /**
             * 0–1。<0.3 只有鋪底；0.3–0.6 加入鋼琴、貝斯與輕鼓；≥0.6 完整鼓組與旋律；≥0.85 旋律移高。進入能量較高的段落前會漸強、過門並加鈸。
             */
            energy: number;
            /**
             * 最後一小節收尾：延長主和弦、鼓只敲一下。
             */
            ending?: boolean;
            /**
             * Agent 自己寫的旋律，取代自動旋律（不論 energy 都演奏）。每個音寫成 音名八度/時值：C5/4 四分音符、F#4/8 八分、Bb4/2. 附點二分、r/4 四分休止；| 分隔小節，每小節要剛好 4 拍；C4 為中央 C，音域 G3–G6。比段落短時循環。
             */
            melody?: string;
          },
          ...{
            name?: string;
            bars?: number;
            /**
             * @minItems 1
             */
            scenes?: [string, ...string[]];
            /**
             * 每小節一個和弦，不足時循環。例：C、Am、F#m、Bb、G7、Cmaj7、Dsus4。
             *
             * @minItems 1
             * @maxItems 16
             */
            chords:
              | [string]
              | [string, string]
              | [string, string, string]
              | [string, string, string, string]
              | [string, string, string, string, string]
              | [string, string, string, string, string, string]
              | [string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string, string, string, string]
              | [string, string, string, string, string, string, string, string, string, string, string, string, string]
              | [
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string
                ]
              | [
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string
                ]
              | [
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string,
                  string
                ];
            /**
             * 0–1。<0.3 只有鋪底；0.3–0.6 加入鋼琴、貝斯與輕鼓；≥0.6 完整鼓組與旋律；≥0.85 旋律移高。進入能量較高的段落前會漸強、過門並加鈸。
             */
            energy: number;
            /**
             * 最後一小節收尾：延長主和弦、鼓只敲一下。
             */
            ending?: boolean;
            /**
             * Agent 自己寫的旋律，取代自動旋律（不論 energy 都演奏）。每個音寫成 音名八度/時值：C5/4 四分音符、F#4/8 八分、Bb4/2. 附點二分、r/4 四分休止；| 分隔小節，每小節要剛好 4 拍；C4 為中央 C，音域 G3–G6。比段落短時循環。
             */
            melody?: string;
          }[]
        ];
      };
    };
    /**
     * 字幕設定，只在 assemble 階段使用，不納入 scene 的 inputHash（SPEC §7.5）。
     */
    captions?: {
      mode?: "srt" | "burn" | "none";
      style?: {
        fontFamily?: string;
        fontSize?: number;
        position?: "bottom" | "middle" | "top";
      };
    };
    /**
     * 專案預設 TTS（SPEC §7.4），scene 可覆寫。
     */
    tts: {
      /**
       * 見 SPEC §7.4。
       */
      provider:
        "edge-tts" | "azure" | "openai" | "elevenlabs" | "piper" | "system" | "manual" | "cosyvoice3" | "cosyvoice";
      voice?: string;
      /**
       * 全域專有名詞發音校正對照表：{ "原字/詞": "發音替換字或注音" }，用以分離字幕與發音文本。
       */
      pronunciation?: {
        [k: string]: string | undefined;
      };
      /**
       * 連網 TTS 的使用者同意紀錄。
       */
      consent?: {
        onlineTts: boolean;
        /**
         * ISO 8601 / RFC 3339 日期時間，須含時區。
         */
        grantedAt?: string;
      };
    };
    /**
     * ASR 語音辨識與發音校正設定。
     */
    asr?: {
      provider?: "none" | "qwen-asr" | "whisper-cli" | "faster-whisper" | "openai" | "fake";
      /**
       * ASR 模型：依硬體預設推薦 Qwen/Qwen3-ASR-1.7B（具備 GPU）或 Qwen/Qwen3-ASR-0.6B（CPU/輕量環境）。
       */
      model?: "Qwen/Qwen3-ASR-1.7B" | "Qwen/Qwen3-ASR-0.6B" | "custom";
      autoPatch?: boolean;
      /**
       * 本地 ASR 模型安裝或連網 ASR 的使用者同意紀錄。
       */
      consent?: {
        installAsr: boolean;
        /**
         * ISO 8601 / RFC 3339 日期時間，須含時區。
         */
        grantedAt?: string;
      };
    };
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * 陣列順序即影片播放順序。
   */
  scenes: {
    id: string;
    /**
     * scene 目錄，格式 scenes/{三位數}-{slug}。目錄編號為建立時的序號，不代表目前順序。
     */
    dir: string;
  }[];
  /**
   * SPEC §4.5。
   */
  status:
    | "initialized"
    | "analyzed"
    | "designed"
    | "script_generated"
    | "producing"
    | "ready_to_assemble"
    | "completed"
    | "failed";
  /**
   * ISO 8601 / RFC 3339 日期時間，須含時區。
   */
  updatedAt: string;
  /**
   * 最後寫入者：agent（Agent 經 state.mjs）、user（Web UI 或手動）、mcp。companion 為已移除的本機助手所寫，僅為相容舊專案保留。
   */
  updatedBy: "agent" | "user" | "companion" | "mcp";
  /**
   * This interface was referenced by `VideoProjectJson`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}

/**
 * 單一 scene 的定義與狀態（SPEC §4.2）。路徑相對於 scene 目錄；以 `@/` 開頭則相對於專案根目錄。
 */
export interface SceneJson {
  id: string;
  title: string;
  purpose:
    | "hook"
    | "problem"
    | "solution"
    | "feature"
    | "how-it-works"
    | "benefit"
    | "social-proof"
    | "cta"
    | "opening"
    | "setup"
    | "conflict"
    | "climax"
    | "resolution"
    | "ending"
    | "custom";
  narration: {
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    scriptFile: string;
    /**
     * 省略時沿用 project.tts.provider。
     */
    provider?:
      "edge-tts" | "azure" | "openai" | "elevenlabs" | "piper" | "system" | "manual" | "cosyvoice3" | "cosyvoice";
    /**
     * 省略時沿用 project.tts.voice。
     */
    voice?: string;
    speed?: number;
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    audioFile?: string;
    /**
     * Scene 專屬發音補丁對照表：{ "原字/詞": "發音替換字或注音" }。
     */
    pronunciation?: {
      [k: string]: string | undefined;
    };
  };
  /**
   * 以 `x-` 開頭的欄位保留給使用者或第三方工具自訂，Agent 必須原樣保留。
   */
  visual: {
    /**
     * web-capture：Playwright 錄製網頁操作；screenshot：靜態截圖 + 動效；motion-graphic：純動畫（可用 motion 指定自寫的動畫模組）；code：程式碼展示；user-asset：使用者提供的影片或圖片。
     */
    type: "web-capture" | "screenshot" | "motion-graphic" | "code" | "user-asset";
    /**
     * 給人與 Agent 讀的畫面描述。
     */
    description: string;
    capture?: {
      url: string;
      /**
       * 省略時使用 project.format 的寬高。
       */
      viewport?: {
        width: number;
        height: number;
      };
      actions?: {
        do: "navigate" | "scroll" | "click" | "hover" | "type" | "highlight" | "script" | "wait";
        url?: string;
        selector?: string;
        text?: string;
        /**
         * script 動作在頁面中執行的 JavaScript 檔（例如在資料很少的報表頁填入示意資料）。需要 capture.domEditConsent。
         */
        file?: string;
        /**
         * scroll 的絕對捲動位置（px），與 selector 擇一。
         */
        y?: number;
        /**
         * wait 的毫秒數；highlight 時為框住後停留的毫秒數（預設 1200）。
         */
        ms?: number;
        /**
         * true 時把這個動作從開始到結束（含等待頁面穩定）整段從錄影剪掉。Agent 判斷該段畫面沒有意義時使用，例如單頁應用切換路由的過場、載入中的骨架畫面。
         */
        cut?: boolean;
      }[];
      /**
       * 使用者同意在錄製時以 script 動作修改頁面內容（例如填入示意資料）的紀錄。
       */
      domEditConsent?: {
        granted: boolean;
        /**
         * ISO 8601 / RFC 3339 日期時間，須含時區。
         */
        grantedAt?: string;
      };
    };
    /**
     * 程式碼展示，file 與 content 擇一。
     */
    code?: {
      /**
       * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
       */
      file?: string;
      content?: string;
      language: string;
      highlightLines?: number[];
    };
    asset?: {
      /**
       * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
       */
      src: string;
      kind: "image" | "video";
      trimStartSec?: number;
      trimEndSec?: number;
      fit?: "contain" | "cover";
    };
    /**
     * motion-graphic 的自訂動畫：Agent 撰寫的 JavaScript 模組（SVG、Canvas、GSAP、Three.js、GLSL、Rough.js 等），取代預設的漸層背景，elements 仍疊加在上面。模組要求見 Skill rendering-guide.md#motion。
     */
    motion?: {
      /**
       * ES module，預設匯出 setup(ctx)，回傳 seek(t)。通常放在 assets/motion.js。
       */
      file: string;
      /**
       * 模組匯入的共用檔案或資料夾（例如 @/assets/cast/fox/），納入 inputHash：這些檔案一改，scene 就需要重做。資料夾以 / 結尾，包含底下所有檔案。
       */
      uses?: string[];
    };
    /**
     * 疊加在畫面上的元素。
     */
    elements?: {
      type: "text" | "image" | "video";
      /**
       * type = text 時的文字。
       */
      content?: string;
      /**
       * type = image / video 時的來源。
       */
      src?: string;
      /**
       * 出現時間（scene 內相對秒數）。
       */
      at: number;
      /**
       * 顯示秒數；省略則持續到 scene 結束。
       */
      duration?: number;
      /**
       * type = text 的字級。large / xl 放大，但會自動縮回到不超過兩行、不超出畫面。
       */
      size?: "normal" | "large" | "xl";
      animation?:
        "none" | "fadeIn" | "slideInLeft" | "slideInRight" | "slideInUp" | "slideInDown" | "zoomIn" | "typewriter";
      /**
       * 預設位置，或以畫面百分比指定的自訂座標（元素中心點）。
       */
      position?:
        | ("center" | "top" | "bottom" | "left" | "right" | "top-left" | "top-right" | "bottom-left" | "bottom-right")
        | {
            x: number;
            y: number;
          };
    }[];
    /**
     * 進場轉場；第一個 scene 的轉場會被忽略。
     */
    transitionIn?: "none" | "fade" | "slide-left" | "slide-right" | "wipe" | "zoom";
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * null：由旁白音長 + 0.5 秒決定；數值：強制秒數。幀數一律由 durationSec × fps 推得，不儲存。
   */
  durationSec: number | null;
  /**
   * SPEC §4.5。
   */
  status: "draft" | "assets_ready" | "rendering" | "rendered" | "approved" | "stale" | "failed";
  /**
   * 最近一次成功渲染的紀錄。stale 時保留舊紀錄以供比對。
   */
  render?: {
    /**
     * SPEC §4.2：對 scene.json（排除 status、render、error、attempts、locked、feedback、updatedAt、updatedBy）、旁白稿、scene 素材、project.format 計算。
     */
    inputHash: string;
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    outputFile: string;
    /**
     * ISO 8601 / RFC 3339 日期時間，須含時區。
     */
    renderedAt: string;
    actualDurationSec?: number;
  } | null;
  /**
   * true 時 Agent 不得修改此 scene，除非使用者明確要求。不納入 inputHash。
   */
  locked: boolean;
  error?: {
    step: "tts" | "capture" | "render" | "validate" | "other";
    message: string;
    /**
     * ISO 8601 / RFC 3339 日期時間，須含時區。
     */
    at: string;
    /**
     * 給使用者的重試或修正建議。
     */
    hint?: string;
  } | null;
  /**
   * 使用者在網頁上看這一段影片時留的意見，可指出時間點與畫面位置（SPEC §9.3）。Agent 重做這一段時逐條處理，處理完填 resolvedAt 與 reply；不刪除。不納入 inputHash。
   */
  feedback?: {
    id: string;
    /**
     * 使用者的意見，原話。
     */
    text: string;
    /**
     * 意見指的時間點，相對於這一段影片開頭（秒）。
     */
    atSec?: number;
    /**
     * 意見指的畫面位置，以畫面寬高的比例表示（左上角為 0,0）。
     */
    point?: {
      x: number;
      y: number;
    };
    /**
     * ISO 8601 / RFC 3339 日期時間，須含時區。
     */
    createdAt: string;
    /**
     * Agent 處理完的時間；null 或不存在表示尚未處理。
     */
    resolvedAt?: string | null;
    /**
     * Agent 給使用者的簡短說明：改了什麼，或為什麼沒改。
     */
    reply?: string;
  }[];
  /**
   * 連續失敗次數，成功後歸零。Agent 自動重試上限 2 次（SPEC §8.1 規則 10）。
   */
  attempts?: number;
  /**
   * ISO 8601 / RFC 3339 日期時間，須含時區。
   */
  updatedAt?: string;
  /**
   * 最後寫入者：agent（Agent 經 state.mjs）、user（Web UI 或手動）、mcp。companion 為已移除的本機助手所寫，僅為相容舊專案保留。
   */
  updatedBy?: "agent" | "user" | "companion" | "mcp";
  /**
   * This interface was referenced by `SceneJson`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}

/**
 * Agent 目前在做什麼、是否在等使用者回覆（SPEC §9.2）。只有 Agent 寫入、網頁只讀；不納入版本控制。專案建立前就可以存在（與 video.start.json 並列）。
 */
export interface VideoActivityJson {
  /**
   * 給使用者看的一句白話，例如「正在錄第 3 段的畫面」「分鏡寫好了，請在對話中確認」。
   */
  message: string;
  /**
   * true：Agent 停下來等使用者在對話中回覆（checkpoint、gate、提問）。
   */
  waitingForUser: boolean;
  /**
   * 目前的工作流程步驟或操作（workflow.json 的 id）；不在任何步驟時為 null。
   */
  step?: string | null;
  /**
   * 正在處理的 scene；沒有時為 null。
   */
  scene?: string | null;
  /**
   * ISO 8601 / RFC 3339 日期時間，須含時區。
   */
  updatedAt: string;
}
