// Generated by tools/gen-types.mjs from specs/*.schema.json. Do not edit; run `pnpm run gen:types`.
/* eslint-disable */

/**
 * 專案層級定義與 scene 播放順序。scene 內容與狀態存於各自的 scene.json（SPEC §4.1）。
 */
export interface VideoProjectJson {
  specVersion: string;
  /**
   * 以 `x-` 開頭的欄位保留給使用者或第三方工具自訂，Agent 必須原樣保留。
   */
  project: {
    id: string;
    name: string;
    /**
     * 至少提供一種產品來源。
     */
    sources: {
      productUrl?: string | null;
      /**
       * 產品原始碼位置，唯讀輸入，可在專案外（相對或絕對路徑）。
       */
      sourceCodePath?: string | null;
      description?: string | null;
      /**
       * 風格參考影片（可選，SPEC §6.2 Step 2）。
       */
      referenceVideoUrl?: string | null;
    };
    targetAudience?: string;
    /**
     * BCP 47 語言標籤，例如 zh-TW、en、en-US。
     */
    language: string;
    /**
     * 由 /video-translate 產生時記錄來源專案（SPEC §4.4）。
     */
    translatedFrom?: {
      id: string;
      /**
       * BCP 47 語言標籤，例如 zh-TW、en、en-US。
       */
      language: string;
    };
    /**
     * 寬高須符合 aspectRatio（由 validate.mjs 檢查）。H.264 需偶數寬高。
     */
    format: {
      aspectRatio: "16:9" | "9:16" | "1:1" | "4:5";
      width: number;
      height: number;
      fps: 24 | 25 | 30 | 50 | 60;
      targetDurationSec?: number;
    };
    /**
     * BGM 設定，只在 assemble 階段使用（SPEC §7.5）。
     */
    audio?: {
      /**
       * 相對於專案根目錄；null 或檔案不存在時略過 BGM。
       */
      bgm?: string | null;
      bgmVolume?: number;
      ducking?: boolean;
    };
    /**
     * 字幕設定，只在 assemble 階段使用，不納入 scene 的 inputHash（SPEC §7.5）。
     */
    captions?: {
      mode?: "srt" | "burn" | "none";
      style?: {
        fontFamily?: string;
        fontSize?: number;
        position?: "bottom" | "middle" | "top";
      };
    };
    /**
     * 專案預設 TTS（SPEC §7.4），scene 可覆寫。
     */
    tts: {
      /**
       * 見 SPEC §7.4。
       */
      provider: "edge-tts" | "azure" | "openai" | "elevenlabs" | "piper" | "system" | "manual";
      voice?: string;
      /**
       * 連網 TTS 的使用者同意紀錄。
       */
      consent?: {
        onlineTts: boolean;
        /**
         * ISO 8601 / RFC 3339 日期時間，須含時區。
         */
        grantedAt?: string;
      };
    };
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * 陣列順序即影片播放順序。
   */
  scenes: {
    id: string;
    /**
     * scene 目錄，格式 scenes/{三位數}-{slug}。目錄編號為建立時的序號，不代表目前順序。
     */
    dir: string;
  }[];
  /**
   * SPEC §4.5。
   */
  status: "initialized" | "analyzed" | "script_generated" | "producing" | "ready_to_assemble" | "completed" | "failed";
  /**
   * ISO 8601 / RFC 3339 日期時間，須含時區。
   */
  updatedAt: string;
  /**
   * 最後寫入者：agent（Agent 經 state.mjs）、user（Web UI 或手動）、companion、mcp。
   */
  updatedBy: "agent" | "user" | "companion" | "mcp";
  /**
   * This interface was referenced by `VideoProjectJson`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}

/**
 * 單一 scene 的定義與狀態（SPEC §4.2）。路徑相對於 scene 目錄；以 `@/` 開頭則相對於專案根目錄。
 */
export interface SceneJson {
  id: string;
  title: string;
  purpose: "hook" | "problem" | "solution" | "feature" | "how-it-works" | "benefit" | "social-proof" | "cta" | "custom";
  narration: {
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    scriptFile: string;
    /**
     * 省略時沿用 project.tts.provider。
     */
    provider?: "edge-tts" | "azure" | "openai" | "elevenlabs" | "piper" | "system" | "manual";
    /**
     * 省略時沿用 project.tts.voice。
     */
    voice?: string;
    speed?: number;
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    audioFile?: string;
  };
  /**
   * 以 `x-` 開頭的欄位保留給使用者或第三方工具自訂，Agent 必須原樣保留。
   */
  visual: {
    /**
     * web-capture：Playwright 錄製網頁操作；screenshot：靜態截圖 + 動效；motion-graphic：純動畫；code：程式碼展示；user-asset：使用者提供的影片或圖片。
     */
    type: "web-capture" | "screenshot" | "motion-graphic" | "code" | "user-asset";
    /**
     * 給人與 Agent 讀的畫面描述。
     */
    description: string;
    capture?: {
      url: string;
      /**
       * 省略時使用 project.format 的寬高。
       */
      viewport?: {
        width: number;
        height: number;
      };
      actions?: {
        do: "navigate" | "scroll" | "click" | "hover" | "type" | "highlight" | "wait";
        url?: string;
        selector?: string;
        text?: string;
        /**
         * scroll 的絕對捲動位置（px），與 selector 擇一。
         */
        y?: number;
        ms?: number;
      }[];
    };
    /**
     * 程式碼展示，file 與 content 擇一。
     */
    code?: {
      /**
       * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
       */
      file?: string;
      content?: string;
      language: string;
      highlightLines?: number[];
    };
    asset?: {
      /**
       * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
       */
      src: string;
      kind: "image" | "video";
      trimStartSec?: number;
      trimEndSec?: number;
      fit?: "contain" | "cover";
    };
    /**
     * 疊加在畫面上的元素。
     */
    elements?: {
      type: "text" | "image" | "video";
      /**
       * type = text 時的文字。
       */
      content?: string;
      /**
       * type = image / video 時的來源。
       */
      src?: string;
      /**
       * 出現時間（scene 內相對秒數）。
       */
      at: number;
      /**
       * 顯示秒數；省略則持續到 scene 結束。
       */
      duration?: number;
      animation?:
        "none" | "fadeIn" | "slideInLeft" | "slideInRight" | "slideInUp" | "slideInDown" | "zoomIn" | "typewriter";
      /**
       * 預設位置，或以畫面百分比指定的自訂座標（元素中心點）。
       */
      position?:
        | ("center" | "top" | "bottom" | "left" | "right" | "top-left" | "top-right" | "bottom-left" | "bottom-right")
        | {
            x: number;
            y: number;
          };
    }[];
    /**
     * 進場轉場；第一個 scene 的轉場會被忽略。
     */
    transitionIn?: "none" | "fade" | "slide-left" | "slide-right" | "wipe" | "zoom";
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * null：由旁白音長 + 0.5 秒決定；數值：強制秒數。幀數一律由 durationSec × fps 推得，不儲存。
   */
  durationSec: number | null;
  /**
   * SPEC §4.5。
   */
  status: "draft" | "assets_ready" | "rendering" | "rendered" | "approved" | "stale" | "failed";
  /**
   * 最近一次成功渲染的紀錄。stale 時保留舊紀錄以供比對。
   */
  render?: {
    /**
     * SPEC §4.2：對 scene.json（排除 status、render、error、attempts、locked、updatedAt、updatedBy）、旁白稿、scene 素材、project.format 計算。
     */
    inputHash: string;
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    outputFile: string;
    /**
     * ISO 8601 / RFC 3339 日期時間，須含時區。
     */
    renderedAt: string;
    actualDurationSec?: number;
  } | null;
  /**
   * true 時 Agent 不得修改此 scene，除非使用者明確要求。不納入 inputHash。
   */
  locked: boolean;
  error?: {
    step: "tts" | "capture" | "render" | "validate" | "other";
    message: string;
    /**
     * ISO 8601 / RFC 3339 日期時間，須含時區。
     */
    at: string;
    /**
     * 給使用者的重試或修正建議。
     */
    hint?: string;
  } | null;
  /**
   * 連續失敗次數，成功後歸零。Agent 自動重試上限 2 次（SPEC §8.1 規則 10）。
   */
  attempts?: number;
  /**
   * ISO 8601 / RFC 3339 日期時間，須含時區。
   */
  updatedAt?: string;
  /**
   * 最後寫入者：agent（Agent 經 state.mjs）、user（Web UI 或手動）、companion、mcp。
   */
  updatedBy?: "agent" | "user" | "companion" | "mcp";
  /**
   * This interface was referenced by `SceneJson`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
