// Generates apps/web/src/types/protocol.ts from specs/*.schema.json (SPEC §9.4: types are generated,
// never hand-written, so the UI tracks the protocol).
//
//   node tools/gen-types.mjs           write the file
//   node tools/gen-types.mjs --check   exit 1 when the file is out of date (used by tests / CI)
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from 'json-schema-to-typescript'

const root = fileURLToPath(new URL('../', import.meta.url))
const specs = join(root, 'specs')
const target = join(root, 'apps', 'web', 'src', 'types', 'protocol.ts')
const read = (f) => JSON.parse(readFileSync(join(specs, f), 'utf8'))

/** Resolves `common.schema.json#/$defs/x` and local `#/$defs/x` refs by inlining; drops keywords the generator does not need. */
function prepare(schema, file) {
  const docs = { 'common.schema.json': read('common.schema.json'), [file]: schema }
  const lookup = (doc, pointer) => pointer.split('/').filter(Boolean).reduce((node, key) => node[key], doc)
  const walk = (node, current, depth = 0) => {
    if (Array.isArray(node)) return node.map((n) => walk(n, current, depth))
    if (!node || typeof node !== 'object') return node
    if (typeof node.$ref === 'string' && depth < 20) {
      const [refFile, pointer = ''] = node.$ref.split('#')
      const docName = refFile || current
      const { $ref, ...rest } = node
      const target = walk(lookup(docs[docName], pointer), docName, depth + 1)
      // A $ref next to other keywords (e.g. extensions + properties) merges both.
      return Object.keys(rest).length ? { ...target, ...walk(rest, current, depth), properties: { ...target.properties, ...walk(rest.properties ?? {}, current, depth) } } : target
    }
    const out = {}
    // On an object that defines its own `properties`, anyOf/oneOf are validation rules ("at least
    // one of", "file or content"), not alternative shapes; they must not turn it into a union type.
    const constraintOnly = node.properties && typeof node.properties === 'object'
    for (const [k, v] of Object.entries(node)) {
      if (['$defs', 'if', 'then', 'else', '$id', '$schema', 'allOf', 'not'].includes(k)) continue
      if ((k === 'anyOf' || k === 'oneOf') && constraintOnly) continue
      out[k] = walk(v, current, depth)
    }
    if (out.unevaluatedProperties === false) {
      delete out.unevaluatedProperties
      out.additionalProperties = false
    }
    return out
  }
  return walk(schema, file)
}

async function generate() {
  const options = { bannerComment: '', additionalProperties: false, strictIndexSignatures: true, format: true, unknownAny: true }
  const project = await compile(prepare(read('project.schema.json'), 'project.schema.json'), 'VideoProject', options)
  const scene = await compile(prepare(read('scene.schema.json'), 'scene.schema.json'), 'Scene', options)
  return `// Generated by tools/gen-types.mjs from specs/*.schema.json. Do not edit; run \`pnpm run gen:types\`.
/* eslint-disable */

${project}
${scene}`
}

const text = await generate()
if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(target, 'utf8')
  } catch {}
  if (current !== text) {
    console.error('apps/web/src/types/protocol.ts is out of date; run pnpm run gen:types')
    process.exit(1)
  }
  console.log('✓ apps/web/src/types/protocol.ts is up to date')
} else {
  writeFileSync(target, text)
  console.log('wrote apps/web/src/types/protocol.ts')
}
