// Generates apps/slide/src/types/protocol.ts from specs/*.schema.json
//
//   node apps/slide/tools/gen-types.mjs           write the file
//   node apps/slide/tools/gen-types.mjs --check   exit 1 when out of date
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from 'json-schema-to-typescript'

const appDir = fileURLToPath(new URL('../', import.meta.url))
const specs = join(appDir, 'specs')
const target = join(appDir, 'src', 'types', 'protocol.ts')
const read = (f) => JSON.parse(readFileSync(join(specs, f), 'utf8'))

async function generate() {
  const options = { bannerComment: '', additionalProperties: false, strictIndexSignatures: true, format: true, unknownAny: true }
  const project = await compile(read('project.schema.json'), 'SlideProject', options)
  const activity = await compile(read('activity.schema.json'), 'SlideActivity', options)
  return `// Generated by apps/slide/tools/gen-types.mjs from specs/*.schema.json. Do not edit.
/* eslint-disable */

${project}
${activity}`
}

const text = await generate()
if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(target, 'utf8')
  } catch {}
  if (current !== text) {
    console.error('apps/slide/src/types/protocol.ts is out of date; run node apps/slide/tools/gen-types.mjs')
    process.exit(1)
  }
  console.log('✓ apps/slide/src/types/protocol.ts is up to date')
} else {
  mkdirSync(join(appDir, 'src', 'types'), { recursive: true })
  writeFileSync(target, text)
  console.log('wrote apps/slide/src/types/protocol.ts')
}
